# Generated by Django 4.1 on 2022-08-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoAmericana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_operacao', models.DateField()),
                ('unidades', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ações Americanas',
            },
        ),
        migrations.CreateModel(
            name='AcaoFii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_operacao', models.DateField()),
                ('unidades', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ações, BDRs, ETFs ou FIIs',
            },
        ),
        migrations.CreateModel(
            name='Criptomoeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('data_operacao', models.DateField()),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=11)),
                ('unidades', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Criptomoedas',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200)),
                ('data_operacao', models.DateField()),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='RendaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(choices=[('cdb', 'CDB'), ('rdb', 'RDB'), ('lc', 'LC'), ('lci', 'LCI'), ('lca', 'LCA'), ('lig', 'LIG'), ('cpr', 'CPR'), ('cri', 'CRI'), ('cra', 'CRA')], max_length=3)),
                ('emissor', models.CharField(max_length=64)),
                ('data_operacao', models.DateField()),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipo_aplicacao', models.CharField(choices=[('pre', 'PRÉ'), ('cdi', 'CDI'), ('cdi+', 'CDI+'), ('ipca+', 'IPCA+'), ('selic', 'SELIC'), ('selic+', 'SELIC+'), ('igpm+', 'IGPM+'), ('igpdi+', 'IGPDI+')], max_length=6)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=11)),
                ('vencimento', models.DateField()),
                ('liquidez', models.CharField(max_length=64)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rendas Fixas',
            },
        ),
        migrations.CreateModel(
            name='TesouroDireto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('data_operacao', models.DateField()),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=11)),
                ('unidades', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipo_aplicacao', models.CharField(choices=[('pre', 'PRÉ'), ('cdi', 'CDI'), ('cdi+', 'CDI+'), ('ipca+', 'IPCA+'), ('selic', 'SELIC'), ('selic+', 'SELIC+'), ('igpm+', 'IGPM+'), ('igpdi+', 'IGPDI+')], max_length=6)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=11)),
                ('vencimento', models.DateField()),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tesouros Diretos',
            },
        ),
    ]
