# Generated by Django 4.1 on 2023-03-02 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('desempenho', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListAcaoAmericana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, verbose_name='Ticker')),
                ('empresa', models.CharField(max_length=50, verbose_name='Nome da Empresa')),
                ('preco_fechamento', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP Ação Americana ',
                'verbose_name_plural': 'IP Ações Americanas',
            },
        ),
        migrations.CreateModel(
            name='ListAcaoFii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, verbose_name='Ticker')),
                ('empresa', models.CharField(max_length=50, verbose_name='Nome da Empresa')),
                ('preco_fechamento', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP Ação ou Fii',
                'verbose_name_plural': 'IP Ações e Fiis',
            },
        ),
        migrations.CreateModel(
            name='TesouroDireto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome do Título')),
                ('data_operacao', models.DateField()),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipo_aplicacao', models.CharField(choices=[('pre', 'PRÉ'), ('cdi', 'CDI'), ('cdi+', 'CDI+'), ('ipca+', 'IPCA+'), ('selic', 'SELIC'), ('selic+', 'SELIC+'), ('igpm+', 'IGPM+'), ('igpdi+', 'IGPDI+')], max_length=6)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=11)),
                ('vencimento', models.DateField()),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.carteira')),
            ],
            options={
                'verbose_name_plural': 'Tesouros Diretos',
            },
        ),
        migrations.CreateModel(
            name='RendaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('cdb', 'CDB'), ('rdb', 'RDB'), ('lc', 'LC'), ('lci', 'LCI'), ('lca', 'LCA'), ('lig', 'LIG'), ('cpr', 'CPR'), ('cri', 'CRI'), ('cra', 'CRA')], max_length=3, verbose_name='Produto')),
                ('emissor', models.CharField(max_length=64)),
                ('data_operacao', models.DateField()),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipo_aplicacao', models.CharField(choices=[('pre', 'PRÉ'), ('cdi', 'CDI'), ('cdi+', 'CDI+'), ('ipca+', 'IPCA+'), ('selic', 'SELIC'), ('selic+', 'SELIC+'), ('igpm+', 'IGPM+'), ('igpdi+', 'IGPDI+')], max_length=6)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=11)),
                ('vencimento', models.DateField()),
                ('liquidez', models.CharField(max_length=64)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.carteira')),
            ],
            options={
                'verbose_name_plural': 'Rendas Fixas',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=200, verbose_name='Descrição')),
                ('data_operacao', models.DateField()),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.carteira')),
            ],
            options={
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='Criptomoeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('data_operacao', models.DateField()),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=11)),
                ('unidades', models.DecimalField(decimal_places=10, max_digits=13)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.carteira')),
            ],
            options={
                'verbose_name_plural': 'Criptomoedas',
            },
        ),
        migrations.CreateModel(
            name='AcaoFii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_operacao', models.DateField()),
                ('unidades', models.IntegerField()),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.carteira')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.listacaofii', verbose_name='Ticker')),
            ],
            options={
                'verbose_name': 'Ação e FII',
                'verbose_name_plural': 'Ações e FIIs',
            },
        ),
        migrations.CreateModel(
            name='AcaoAmericana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_operacao', models.DateField()),
                ('unidades', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.carteira')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.listacaoamericana', verbose_name='Ticker')),
            ],
            options={
                'verbose_name_plural': 'Ações Americanas',
            },
        ),
    ]
