# Generated by Django 4.1 on 2022-09-19 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='acaoamericana',
            name='carteira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.carteira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaofii',
            name='carteira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.carteira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criptomoeda',
            name='carteira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.carteira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propriedade',
            name='carteira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.carteira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendafixa',
            name='carteira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.carteira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tesourodireto',
            name='carteira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.carteira'),
            preserve_default=False,
        ),
    ]
