# Generated by Django 4.1 on 2022-09-22 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='rendafixa',
            name='produto',
        ),
        migrations.AddField(
            model_name='propriedade',
            name='nome',
            field=models.TextField(default='', max_length=200, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendafixa',
            name='nome',
            field=models.CharField(choices=[('cdb', 'CDB'), ('rdb', 'RDB'), ('lc', 'LC'), ('lci', 'LCI'), ('lca', 'LCA'), ('lig', 'LIG'), ('cpr', 'CPR'), ('cri', 'CRI'), ('cra', 'CRA')], default='', max_length=3, verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acaoamericana',
            name='nome',
            field=models.CharField(max_length=64, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='acaofii',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.carteira'),
        ),
        migrations.AlterField(
            model_name='acaofii',
            name='nome',
            field=models.CharField(max_length=64, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tesourodireto',
            name='nome',
            field=models.CharField(max_length=64, verbose_name='Nome do Título'),
        ),
    ]
