# Generated by Django 4.1 on 2023-03-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCriptomoeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, verbose_name='Ticker')),
                ('preco_fechamento', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP Ação Americana ',
                'verbose_name_plural': 'IP Ações Americanas',
            },
        ),
    ]
