# Generated by Django 4.1 on 2022-09-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_carteira_acaoamericana_carteira_acaofii_carteira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='nome',
            field=models.CharField(default='adas', max_length=64),
            preserve_default=False,
        ),
    ]
