# Generated by Django 4.1 on 2023-03-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_listcriptomoeda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcriptomoeda',
            options={'verbose_name': 'IP Criptomoedas', 'verbose_name_plural': 'IP Criptomoedas'},
        ),
        migrations.AlterField(
            model_name='criptomoeda',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.listcriptomoeda', verbose_name='Ticker'),
        ),
    ]
