# Generated by Django 4.1 on 2023-03-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_extrato_rentabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='carteira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extrato', to='assets.carteira'),
            preserve_default=False,
        ),
    ]
