# Generated by Django 4.1 on 2023-02-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_carteira_desempenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='b3acaofii',
            name='preco_fechamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
