# Generated by Django 4.1 on 2023-04-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_extrato_carteira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='unidades',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
