# Generated by Django 4.1 on 2023-04-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_extrato_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendafixa',
            name='nome',
            field=models.CharField(choices=[('CDB', 'CDB'), ('RDB', 'RDB'), ('LC', 'LC'), ('LCI', 'LCI'), ('LCA', 'LCA'), ('LIG', 'LIG'), ('CPR', 'CPR'), ('CRI', 'CRI'), ('CRA', 'CRA')], max_length=3, verbose_name='Produto'),
        ),
    ]
