# Generated by Django 4.1 on 2022-11-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_acaofii_options_alter_criptomoeda_carteira_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesourodireto',
            name='unidades',
        ),
        migrations.AlterField(
            model_name='criptomoeda',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.carteira'),
        ),
    ]
