# Generated by Django 4.1 on 2023-05-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_rendafixa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='desempenho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
