# Generated by Django 4.1 on 2023-01-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_tesourodireto_unidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaofii',
            name='unidades',
            field=models.IntegerField(),
        ),
    ]
