# Generated by Django 4.1 on 2023-02-14 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_acaofii_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='B3AcaoFii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Empresa')),
                ('inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='acaofii',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.b3acaofii', verbose_name='Ticker'),
        ),
    ]
